ProjetoCloud/ProjetoCloud/Controllers/PlanosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Contexto;
using DAL.Entidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoCloud.Models;
using Plano = DAL.Entidades.Plano;

namespace ProjetoCloud.Controllers
{
    public class PlanosController : Controller
    {
        private readonly CloudContexto _context;

        public PlanosController(CloudContexto context)
        {
            _context = context;
        }

        // GET: Planos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Planos.ToListAsync());
        }

        // GET: Planos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plano = await _context.Planos
                .FirstOrDefaultAsync(m => m.Id_Plano == id);
            if (plano == null)
            {
                return NotFound();
            }

            return View(plano);
        }

        // GET: Planos/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Planos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id_Plano,Nome_Plano,Valor_Plano,Qtde_Max_Dispositivos_Plano")] Plano plano)
        {
            if (ModelState.IsValid)
            {
                plano.Data_Cadastro_Plano = DateTime.Now;
                _context.Add(plano);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(plano);
        }

        // GET: Planos/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plano = await _context.Planos.FindAsync(id);
            if (plano == null)
            {
                return NotFound();
            }
            return View(plano);
        }

        // POST: Planos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Plano,Nome_Plano,Valor_Plano,Qtde_Max_Dispositivos_Plano")] Plano plano)
        {
            if (id != plano.Id_Plano)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    plano.Data_Cadastro_Plano = DateTime.Now;
                    _context.Update(plano);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanoExists(plano.Id_Plano))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(plano);
        }

        // GET: Planos/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plano = await _context.Planos
                .FirstOrDefaultAsync(m => m.Id_Plano == id);
            if (plano == null)
            {
                return NotFound();
            }

            return View(plano);
        }

        // POST: Planos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plano = await _context.Planos.FindAsync(id);
            _context.Planos.Remove(plano);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PlanoExists(int id)
        {
            return _context.Planos.Any(e => e.Id_Plano == id);
        }
    }
}

ProjetoCloud/ProjetoCloud/Controllers/UsuariosController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DAL.Contexto;
using DAL.Entidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetoCloud.Areas.Identity.Data;
using ProjetoCloud.ViewModels;

namespace ProjetoCloud.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private readonly CloudContexto _context;
        private readonly UserManager<ProjetoCloudUser> _userManager;

        public UsuariosController(CloudContexto context, UserManager<ProjetoCloudUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            if( User.HasClaim(c => c.Value == "Administrator"))
            {
                return View(await _context.Usuarios.Include(i => i.Plano_Usuario).ToListAsync());
            }
            else
            {
                return Unauthorized();
            }
            
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id_Usuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_Usuario,Nome_Usuario,CPF_Usuario,Cartao_Usuario,CEP_Usuario,Email_Usuario,Senha_Usuario,Adm_Usuario")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.Data_Cadastro_Usuario = DateTime.Now;
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }

            var planos = await _context.Planos.ToListAsync();
            var viewModel = new ViewModelEditarUsuario()
            {
                Usuario = usuario,
                Planos = new SelectList(planos, "Id_Plano", "Nome_Plano"),
                PlanoSelecionado = usuario.Plano_Usuario is null ? 0 : usuario.Plano_Usuario.Id_Plano
            };

            return View(viewModel);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_Usuario,Nome_Usuario,CPF_Usuario,Cartao_Usuario,CEP_Usuario,Email_Usuario,Senha_Usuario,Adm_Usuario,Plano_Usuario")] Usuario usuario, bool Admin, int PlanoSelecionado)
        {
                
            if (id != usuario.Id_Usuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    usuario.Data_Cadastro_Usuario = DateTime.Now;
                    
                    if(PlanoSelecionado > 0)
                    {
                        usuario.Plano_Usuario = _context.Planos.Find(PlanoSelecionado);
                    }

                    _context.Update(usuario);
                    await _context.SaveChangesAsync();

                    var searchUser = _userManager.Users.FirstOrDefault(_ => _.UsuarioId == id);

                    if (searchUser != null)
                    {
                        var usuarioClaims = _userManager.GetClaimsAsync(searchUser).Result;

                        if (usuarioClaims != null)
                        {
                            var adminClaim = usuarioClaims.FirstOrDefault(c => c.Value == "Administrator");

                            if(adminClaim is null && Admin)
                            {
                                await _userManager.AddClaimAsync(searchUser, new Claim(ClaimTypes.Role, "Administrator"));
                            }
                            else if(adminClaim != null && !Admin)
                            {
                                await _userManager.RemoveClaimAsync(searchUser, new Claim(ClaimTypes.Role, "Administrator"));
                            }
                            
                        }
                        
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id_Usuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id_Usuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();


            var searchUser = _userManager.Users.FirstOrDefault(_ => _.UsuarioId == id);

            if (searchUser != null)
            {
                var usuarioClaims = _userManager.GetClaimsAsync(searchUser).Result;

                if (usuarioClaims != null)
                {
                    var adminClaim = usuarioClaims.FirstOrDefault(c => c.Value == "Administrator");

                    if (adminClaim != null)
                    {
                        await _userManager.RemoveClaimAsync(searchUser, new Claim(ClaimTypes.Role, "Administrator"));
                    }

                    await _userManager.DeleteAsync(searchUser);
                }

            }



            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.Id_Usuario == id);
        }
    }
}

ProjetoCloud/ProjetoCloud/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ProjetoCloud.Areas.Identity.Data
@inject SignInManager<ProjetoCloudUser> SignInManager
@inject UserManager<ProjetoCloudUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoCloud</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ProjetoCloud</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (SignInManager.IsSignedIn(User) && User.HasClaim(c => c.Value == "Administrator"))
                    {
                        <li><a asp-area="" asp-controller="Usuarios" asp-action="Index">Usuários</a></li>
                    }

                    <li><a asp-area="" asp-controller="Planos" asp-action="Index">Planos</a></li>

                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li><a asp-area="" asp-controller="Ambientes" asp-action="Index">Ambientes</a></li>
                        <li><a asp-area="" asp-controller="Dispositivos" asp-action="Index">Dispositivos</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content text-center">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - ProjetoCloud</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>